### ISSUE TITLE
SyntaxError in Firefox 72.0.1 

### ISSUE THREAD

**Issue by kastork** [arlac77/multi-path-matcher#61]
When running the example application in `svelte-guard-history-router` per the provided instructions, an error is thrown in this library's code if I open the page in Firefox 72.  The app works without errors in Safari.

Steps:
1. `git clone https://github.com/arlac77/svelte-guard-history-router.git`
2. `cd svelte-guard-history-router`
3. `npm install`
4. `npm start`
5. Visit `http://localhost:5000` in Firefox with developer tools open.

Observe javascript console message:

```
SyntaxError: invalid regexp group multi-path-matcher.mjs:75:11
    pathToRegexp multi-path-matcher.mjs:75
    compile multi-path-matcher.mjs:29
    map self-hosted:251
    compile multi-path-matcher.mjs:29
    Router router.mjs:54
    <anonymous> index.mjs:47
    InnerModuleEvaluation self-hosted:1605
    evaluation self-hosted:1559
```

**Comment by arlac77** [comment]
Looks like FF does not yet support named capture groups

[Bug 1362154](https://bugzilla.mozilla.org/show_bug.cgi?id=1362154)

**Comment by kastork** [comment]
🥳 thanks!
